services:
  discovery1:
    build: .
    container_name: discovery1
    environment:
      - SERVER_PORT=8761
      - EUREKA_HOSTNAME=discovery1
      - EUREKA_SERVICE_URL=http://discovery2:8762/eureka
    ports:
      - "8761:8761"
    networks:
      - reactive-ms-network

  discovery2:
    build: .
    container_name: discovery2
    environment:
      - SERVER_PORT=8762
      - EUREKA_HOSTNAME=discovery2
      - EUREKA_SERVICE_URL=http://discovery1:8761/eureka
    ports:
      - "8762:8762"
    networks:
      - reactive-ms-network

networks:
  reactive-ms-network:
    external: true
